# OKSANA

# Creating a logistic regression to predict absenteeism

# Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

# load the data

In [3]:
data_preprocessed = pd.read_csv('C:/Users/duoxa/Desktop/Absenteeism_datproject_Udemy/df_preprocessed.csv')
data_preprocessed.head()


Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

# Create the targets

In [6]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [10]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>
                 data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [12]:
data_preprocessed['Excessive Absenteeism']=targets

In [14]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# A comments on targets

In [18]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [291]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week','Daily Work Load Average','Distance to Work'],axis=1)

In [293]:
data_with_targets is data_preprocessed

False

In [295]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# Select the inputs for the regression

In [299]:
data_with_targets.shape

(700, 12)

In [301]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [303]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [305]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

# Standardize the data

In [307]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler=StandardScaler()

In [309]:
import numpy as np
import pandas as pd

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin): 
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns
        self.copy = copy         # <--- ADD this line
        self.with_mean = with_mean  # <--- OPTIONAL: add these if you want compatibility
        self.with_std = with_std    # <--- OPTIONAL: add these too
        self.mean_ = None
        self.var_ = None
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns, index=X.index)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [311]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [377]:
columns_to_scale=['Month Value','Transportation Expense','Age', 'Body Mass Index', 'Education', 'Children', 'Pets']
columns_to_omit=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [379]:
absenteeism_scaler= CustomScaler(columns_to_scale)

In [381]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\duoxa\anaconda3\envs\Tensor_Flow_Oks\lib\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Education', 'Children', 'Pets'])

In [383]:
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)

In [385]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431  -0.447980  0.880469   
1                 -1.574681  2.130803         1.002633  -0.447980 -0.019280   
2                 -0.654143  0.248310         1.002633  -0.447980 -0.919030   
3                  0.854936  0.405184        -0.643782  -0.447980  0.880469   
4                  1.005844 -0.536062         0.767431  -0.447980  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186   2.232242  0.880469   
696                0.040034 -1.320435        -0.643782  -0.447980 -0.019280   
697                1.624567 -1.320435        -0.408580   2.232242 -0.919030   
698                0.190942 -0.692937        -0.408580   2.232242 -0.919030   
699                1.036026  0.562059        -0.408580  -0.447980 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [387]:
scaled_inputs.shape

(700, 11)

# Split the data into train & test and shuffle

In [55]:
#Import the relevant module

In [389]:
from sklearn.model_selection import train_test_split

# Split

In [391]:
train_test_split(scaled_inputs,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 438         0         0         0         1    -0.388293   
 365         0         0         0         1    -1.530333   
 166         0         0         0         1    -0.959313   
 622         1         0         0         0    -0.959313   
 106         0         0         0         1     1.610276   
 ..        ...       ...       ...       ...          ...   
 676         0         0         0         1    -0.388293   
 195         0         0         0         1    -0.673803   
 385         0         0         0         1    -1.244823   
 32          0         0         0         1     0.468236   
 495         0         0         0         1     0.753746   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 438               -1.574681  0.091435         0.297027  -0.447980 -0.919030   
 365                0.190942  1.032682         2.649049  -0.447980 -0.019280   
 166                0.5682

In [393]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [395]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [397]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


# Logistic regression with sklearn

In [400]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Training the model

In [403]:
reg=LogisticRegression()

In [405]:
reg.fit(x_train,y_train)

LogisticRegression()

In [407]:
reg.score(x_train,y_train)

0.7732142857142857

### Manually check the accuracy 

In [410]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [412]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [414]:
#Compare model_outputs and targets

In [416]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [418]:
np.sum(model_outputs==y_train)#total number of correct predictions

433

In [420]:
model_outputs.shape[0]

560

In [422]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7732142857142857

# Finding the intercept and coefficients

In [425]:
reg.intercept_

array([-1.67498624])

In [427]:
reg.coef_

array([[ 2.79375844,  0.95359362,  3.10546299,  0.83085358,  0.15852833,
         0.60468158, -0.17056711,  0.27780477, -0.08424352,  0.34734043,
        -0.27736499]])

In [429]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [431]:
feature_name=unscaled_inputs.columns.values

In [433]:
summary_table=pd.DataFrame(columns=['Feature name'],data=feature_name)
                        
summary_table['Coefficient']=np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason_1     2.793758
1                 Reason_2     0.953594
2                 Reason_3     3.105463
3                 Reason_4     0.830854
4              Month Value     0.158528
5   Transportation Expense     0.604682
6                      Age    -0.170567
7          Body Mass Index     0.277805
8                Education    -0.084244
9                 Children     0.347340
10                    Pets    -0.277365

In [435]:
summary_table.index=summary_table.index + 1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.674986
1                 Reason_1     2.793758
2                 Reason_2     0.953594
3                 Reason_3     3.105463
4                 Reason_4     0.830854
5              Month Value     0.158528
6   Transportation Expense     0.604682
7                      Age    -0.170567
8          Body Mass Index     0.277805
9                Education    -0.084244
10                Children     0.347340
11                    Pets    -0.277365

# Interpreting coefficients

In [438]:
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.674986    0.187311
1                 Reason_1     2.793758   16.342326
2                 Reason_2     0.953594    2.595018
3                 Reason_3     3.105463   22.319550
4                 Reason_4     0.830854    2.295277
5              Month Value     0.158528    1.171785
6   Transportation Expense     0.604682    1.830669
7                      Age    -0.170567    0.843186
8          Body Mass Index     0.277805    1.320228
9                Education    -0.084244    0.919207
10                Children     0.347340    1.415298
11                    Pets    -0.277365    0.757778

In [440]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.105463   22.319550
1                 Reason_1     2.793758   16.342326
2                 Reason_2     0.953594    2.595018
4                 Reason_4     0.830854    2.295277
6   Transportation Expense     0.604682    1.830669
10                Children     0.347340    1.415298
8          Body Mass Index     0.277805    1.320228
5              Month Value     0.158528    1.171785
9                Education    -0.084244    0.919207
7                      Age    -0.170567    0.843186
11                    Pets    -0.277365    0.757778
0                Intercept    -1.674986    0.187311

# Testing the  model

In [447]:
reg.score(x_test,y_test)

0.75

In [450]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71328706, 0.28671294],
       [0.5868545 , 0.4131455 ],
       [0.44134189, 0.55865811],
       [0.78134024, 0.21865976],
       [0.08390289, 0.91609711],
       [0.33416409, 0.66583591],
       [0.29892189, 0.70107811],
       [0.13152486, 0.86847514],
       [0.78543137, 0.21456863],
       [0.74884244, 0.25115756],
       [0.493633  , 0.506367  ],
       [0.22472141, 0.77527859],
       [0.07133356, 0.92866644],
       [0.73452626, 0.26547374],
       [0.30947706, 0.69052294],
       [0.54998141, 0.45001859],
       [0.55004133, 0.44995867],
       [0.53881581, 0.46118419],
       [0.40123117, 0.59876883],
       [0.05377404, 0.94622596],
       [0.69951499, 0.30048501],
       [0.78134024, 0.21865976],
       [0.41930999, 0.58069001],
       [0.41930999, 0.58069001],
       [0.24735108, 0.75264892],
       [0.74484338, 0.25515662],
       [0.5097579 , 0.4902421 ],
       [0.85787351, 0.14212649],
       [0.20371958, 0.79628042],
       [0.78134024, 0.21865976],
       [0.

In [452]:
predicted_proba.shape

(140, 2)

In [454]:
predicted_proba[:,1]

array([0.28671294, 0.4131455 , 0.55865811, 0.21865976, 0.91609711,
       0.66583591, 0.70107811, 0.86847514, 0.21456863, 0.25115756,
       0.506367  , 0.77527859, 0.92866644, 0.26547374, 0.69052294,
       0.45001859, 0.44995867, 0.46118419, 0.59876883, 0.94622596,
       0.30048501, 0.21865976, 0.58069001, 0.58069001, 0.75264892,
       0.25515662, 0.4902421 , 0.14212649, 0.79628042, 0.21865976,
       0.37004524, 0.68044644, 0.68566587, 0.52896558, 0.21865976,
       0.53505912, 0.22229498, 0.73722935, 0.40442372, 0.60529027,
       0.21102548, 0.45092708, 0.23833688, 0.40052068, 0.8272578 ,
       0.56837392, 0.69220234, 0.28671294, 0.22009623, 0.20358828,
       0.57467471, 0.32857895, 0.66583591, 0.27021398, 0.83367886,
       0.43525204, 0.88375813, 0.23187918, 0.33499954, 0.34515676,
       0.69712688, 0.6556909 , 0.29299117, 0.79234144, 0.20804092,
       0.26856306, 0.08822409, 0.22229498, 0.73292302, 0.30223781,
       0.22229498, 0.2921123 , 0.90412168, 0.45989651, 0.60157

# Save the model

In [457]:
import pickle

In [463]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [461]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)