In [23]:
#Programming Basics in Python Questions
#Assignment_1 Programming Basics
#Oksana Goljevacki

#1. Create a matrix with three rows A, B and C and four columns with names Q, W, E and R. 
#Fill the matrix with any numbers between 1 and 10.
import numpy as np
rows = ['A', 'B', 'C']
columns = ['Q', 'W', 'E', 'R']
matrix = np.random.randint(1, 11, size=(3, 4))
print (matrix)




[[ 9  2  2  8]
 [10 10  4  7]
 [ 8  3  1  4]]


In [17]:
#2. x = 24, y =”Hello World”, z = 93.65.
#Identify the class of x, y and z and convert all three into factor.
x=24
y ='Hello World'
z = 93.65
import pandas as pd

print(type(x))
print(type(y))
print(type(z))
x_factor=pd.Categorical([x])
y_factor=pd.Categorical([y])
z_factor=pd.Categorical([z])
print(x_factor)
print(y_factor)
print(z_factor)

    


<class 'int'>
<class 'str'>
<class 'float'>
[24]
Categories (1, int64): [24]
['Hello World']
Categories (1, object): ['Hello World']
[93.65]
Categories (1, float64): [93.65]


In [67]:
#3. q = 65.9836
#a. Find square root of q and round it up to 3 digits.
#b. Check if log to the base 10 of q
import math
q = 65.9836
math.sqrt(q)
q1 = 8.123028991700078
rounded_number = round(q1, 3)

import math
q = 65.9836
sqrt_q = math.sqrt(q)
print(sqrt_q)

q1 = 8.123028991700078

rounded_number = round(q1, 3)
print(rounded_number)

import math
q = 65.9836
log_q = math.log10(q)
print(log_q)
#<less than 2

8.123028991700078
8.123
1.819436006533418


In [81]:
#4. x = c(“Intelligence”, “Knowledge”, “Wisdom”, “Comprehension”) 
#y = “I am”
#z = “intelligent”
#a. Find first 4 letters of each word in x.
#b. Combine y and z to form a sentence “I am intelligent”
#c. Convert all the words in x to upper case.
x = ["Intelligence", "Knowledge", "Wisdom", "Comprehension"]
first_four= [word[:4] for word in x]
print(first_four)
y = 'I am'
z = 'intelligent'
sentence = y + " " + z
print(sentence)

x = ["Intelligence", "Knowledge", "Wisdom", "Comprehension"]
UpperCase= [word.upper() for word in x]
print(UpperCase)


['Inte', 'Know', 'Wisd', 'Comp']
I am intelligent
['INTELLIGENCE', 'KNOWLEDGE', 'WISDOM', 'COMPREHENSION']


In [73]:
#5. a = c(3,4,14,17,3,98,66,85,44)
#Print “Yes” if the numbers in ‘a’ are divisible by 3 and “No” if they are not divisible by 3 using ifelse().
a = [3, 4, 14, 17, 3, 98, 66, 85, 44]

for number in a:
    if number % 3 == 0:
        print("Yes")
    else:
        print("No")


Yes
No
No
No
Yes
No
Yes
No
No


In [71]:
#6. b = c(36,3,5,19,2,16,18,41,35,28,30,31)
#List all the numbers less than 30 in b using for loop.

b = [36, 3, 5, 19, 2, 16, 18, 41, 35, 28, 30, 31]
Less30 = []
for number in b:
    if number < 30:
        Less30.append(number)
print(Less30)

[3, 5, 19, 2, 16, 18, 28]


In [21]:
#7. Date = “01/30/18”
#a) Convert Date into standard date format (yyyy-mm-dd) and name it as Date_new.
#b) Extract day of week and month from Date_new.
#c) Find the difference in the current system date and Date_new.
Date_new = datetime.strptime(Date, "%m/%d/%y").strftime("%Y-%m-%d")
print("Date_new:", Date_new)

day_of_week = datetime.strptime(Date_new, "%Y-%m-%d").strftime("%A")
month = datetime.strptime(Date_new, "%Y-%m-%d").strftime("%B")

print("Day of week:", day_of_week)
print("Month:", month)

current_date = datetime.now()
date_new_obj = datetime.strptime(Date_new, "%Y-%m-%d")
difference = current_date - date_new_obj

print("Difference in days:", difference.days)


Date_new: 2018-01-30
Day of week: Tuesday
Month: January
Difference in days: 2575
